[build-system]
requires = ['pytest-runner', 'flake8', 'setuptools', 'wheel']
build-backend = "setuptools.build_meta"

[metadata]
name = 'iplib3'
version = '0.1.5-8'
description = 'A modern, object-oriented approach to IP addresses.'

[tool.coverage]

[tool.coverage.run]
branch = true
relative_files = true